
name: deploy-and-notify
on:
  pull_request:
    branches: [develop]
    
jobs:
  build:
    runs-on: centos-8
    steps:
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set as default
        run: |
          sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
          sudo update-alternatives --install /usr/bin/npm npm /usr/bin/npm 10
      - name: Install project dependencies
        run: yarn install
      - name: Build project
        run: ./build.sh
      - name: Deploy to testing environment
        if: success()
        run: deploy.sh
      - name: Notify team
        if: success()
        uses: microsoft/teams-notification@v1
        with:
          message: "Deployment successful"