---
name: docker-build-and-test.yml

on:
  push:
    branches: [develop]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-build@v1
        with:
          image: node:16-alpine
      - name: Install Dependencies
        run: npm install && npm run build
      - name: Set up Python Build
        uses: docker/setup-build@v1
        with:
          image: python:3.9
      - name: Copy Project Directory
        run: docker cp . my-app
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Build Docker Image
        run: docker build -t my-app:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image to Docker Hub
        run: docker push my-app:latest

  run-integration